version: "3.8"

services:
  phoenix:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: mimir-example-phoenix
    ports:
      - 4000:4000

  mimir:
    image: grafana/mimir
    ports:
      - 9009:9009
    volumes:
      - ./mimir.yaml:/etc/mimir/mimir.yaml
